"""Add photo_url to profiles

Revision ID: 475d215eeab2
Revises: 
Create Date: 2026-04-25 15:08:41.209443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475d215eeab2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('coach_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_profile', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('athlete_profile', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
